---
# vars file for linux-ad-integration

ad_packages:
  - sssd
  - realmd
  - oddjob
  - oddjob-mkhomedir 
  - adcli 
  - samba-common
  - samba-common-tools 
  - krb5-workstation 
  - openldap-clients 
  - policycoreutils-python 