---
# handlers file for linux-ad-integration
- name: restart_sssd
  systemd:
    service: sssd
    state: restarted
    enabled: true

- name: restart_autofs
  systemd:
    service: autofs
    state: restarted
    enabled: true
